config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost', :port => 3000

  root to: "subs#index"

  devise_scope :user do
    # redirect signing out users back to sign-in
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end

  devise_for :users
  resources :users, :only => [:show]
  resources :subs do
    member do
      post "subscribe"
    end
    collection do 
      post "search"
    end
  end
  resources :posts, except: [:index] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  resources :comments, :only => [:create,:show] do 
    member do 
      post "upvote"
      post "downvote"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#  first_name             :string           not null
#  last_name              :string           not null
#  slug                   :string
#  score                  :integer          default(0)
#  admin                  :boolean          default(FALSE)
#
class User < ApplicationRecord
  include Gravtastic
  extend FriendlyId
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :lockable, :timeoutable, :trackable
  before_validation :adding_username
  before_validation :adding_signup_user_points
  friendly_id :username, use: %i[slugged history]

  has_many :subs, :class_name => 'Sub', :primary_key => :id, :foreign_key => :moderator_id, :dependent => :destroy, inverse_of: :moderator
  has_many :posts, :class_name => 'Post', :primary_key => :id, :foreign_key => :author_id, :dependent => :destroy, inverse_of: :author
  has_many :comments, :class_name => 'Comment', :primary_key => :id, :foreign_key => :author_id, :dependent => :destroy
  has_many :votes
  
  gravtastic :secure => true,
    :filetype => :gif,
    :size => 40,
    :default => :monsterid
  

  def last_login!
    if self.last_sign_in_at.hour < Time.now.hour
      ("#{Time.now.min - self.last_sign_in_at.min}hour ago")
    elsif self.last_sign_in_at.day < Time.now.day
      ("#{Time.now.day - self.last_sign_in_at.day}day ago")
    end
  end

  def add_expected_points
    comments_score = self.comments.count
    likes_score = self.votes.where(:value => 1).count
    unlike_score = self.votes.where(:value => -1).count
    total = (comments_score*5) + (likes_score*2) - (unlike_score*2)
    self.score += total
    self.save
  end

  def avatar_thumbnail
    avatar.variant(resize: "150*150!").processed
  end

  def online?
    updated_at > 1.minutes.ago
  end

  def is_admin?
    self.admin ? true : false
  end

  def calculate_votes_post
    total_points = 0
    self.posts.each do |post|
      post_points = post.votes.count
      total_points += post_points
    end
    total_points
  end
  def calculate_votes_comments
    total_points = 0
    self.comments.each do |comment|
      post_points = comment.votes.count
      total_points += post_points
    end
    total_points
  end

  def should_generate_new_friendly_id?
    username_changed? || slug.blank?
  end

  private
  def adding_username
    self.username = "#{self.first_name}".concat(self.last_name)
  end

  def adding_signup_user_points
    self.score = 100
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.friendly.find(params[:id])

        if params[:id] != @user.slug
            return redirect_to @user, :status => :moved_permanently
        end
        @users = User.all
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="bg-white h-[144px] w-full dark:bg-slate-900" data-controller="user"> <!-- The Profile Data -->
  <div class="p-7 font-bold text-2xl lowercase">  <!-- Username and joins -->
    <% if @user.online? %>
      <div class="flex">
        <h4 class="dark:text-white">users/<%= @user.username %></h4>
        <span class="text-green-400 text-sm pl-1">●</span>
      </div>
      <div class="flex">
        <p class="text-blue-400 font-light text-sm pl-2">
          <%= @user.last_login! %>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Score: <span class="text-green-400"><%= @user.score %></span>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Total Post votes: <span class="text-green-400"><%= @user.calculate_votes_post %></span>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Total Comment votes: <span class="text-green-400"><%= @user.calculate_votes_comments %></span>
        </p>
      </div>
    <% else %>
      <div class="flex">
        <h4>users/<%= @user.username %></h4>
        <span class="text-red-400 text-sm pl-1">●</span>
      </div>
      <div class="flex">
        <p class="text-blue-400 font-light text-sm pl-2">
          <%= @user.last_login! %>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Score: <span class="text-green-400"><%= @user.score %></span>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Total Post votes: <span class="text-green-400"><%= @user.calculate_votes_post %></span>
        </p>
        <p class="text-sm ml-1 dark:text-white text-slate-900">
          Total Comment votes: <span class="text-green-400"><%= @user.calculate_votes_comments %></span>
        </p>
      </div>
    <% end %>
    <p class="text-base text-gray-400 hover:text-black
          transition-all duration-700 inline-block group dark:hover:text-white">
      Moderates: <% @user.subs.each do |sub_for_post| %>
        <a class="after:content-['🗡']"
            href="<%= sub_path(sub_for_post.id)%>"
              ><span class="group-hover:text-blue-400 transiton-all duration-700"><%= sub_for_post.title %></span></a>
      <% end %>
    </p>
  </div>
</div>
<section class="grid grid-cols-[400px_auto] dark:bg-slate-900">
  <div class="">  <!-- Posts For the User 100px -->
    <% @user.subs.each do |sub_user|%>
      <div class="block w-[400px] m-[17px] p-3 rounded-lg bg-white text-rose-400 font-bold
            shadow hover:transition-opacity ease-in-out duration-1000
            hover:ease-in-out hover:opacity-100 opacity-50 cursor-pointer
            hover:text-green-400 text-center hover:transition-color ">
        <a href="<%= sub_path(sub_user.id)%>"><p><%= sub_user.title %> 💣</p></a>
      </div>
    <% end %>
    <% @user.comments.where(parent_comment_id: nil).includes(:author).each do |comment|%>
    <div class="bg-white shadow-lg  w-[400px] mt-2 h-[230px] rounded-lg ml-4">
      <div class="flex items-start px-4 py-3 h-20 border-b-2 border-b-gray-400 animate-pulse w-[100%]">
        <img class="w-12 h-12 rounded-full object-cover mr-4 shadow hover:blur-sm hover:cursor-pointer" src="<%= comment.author.gravatar_url %>" alt="user who comment"/>
        <% if comment.author.online? %>
          <div class="flex">
            <h3 class="font-bold pt-2 text-lg inline-block">
              <a href="<%= user_path(comment.author.id) %>">users/<span class="hover:text-blue-300 cursor-pointer"><%= comment.author.username %>
                  </span></a>
            <span class="text-green-400 text-xs top-[-9px] relative ">●</span>
            <p class="text-xs text-slate-500"><span class="hover:text-blue-400"><%= comment.calculate_comment_current_time %></span></p>
          </div>
        <% else %>
          <div class="flex">
            <h3 class="font-bold pt-2 text-lg inline-block">
              <a href="<%= user_path(comment.author.id) %>">users/<span class="hover:text-blue-300 cursor-pointer"><%= comment.author.username %>
                  </span></a>
            <span class="text-rose-400 text-xs top-[-9px] relative ">●</span>
          </div>
        <% end %>
        </h3>
      </div>
      <div class="px-4 py-3 text-sm h-[75px]">
        <%= comment.content %>
      </div>
      <div class="flex mt-7 ml-2 mr-2 justify-between">
        <div class="flex text-gray-700 text-sm mr-3">
                <form method="post" action="<%= upvote_comment_path(comment.id) %>">
                    <input type="hidden"
                            name="authenticity_token"
                            value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-thumbs-up fa-regular fa-xl"></i></button>
                </form>
                <span class="ml-1 text-black font-bold"><%= comment.votes.where(:value => 1).count %></span> <!-- Don't forget to add likes -->
            </div>
            <a href="<%= comment_path(comment) %>" class="font-bold bg-blue-400 p-2 rounded-lg
                        hover:opacity-100 hover:bg-black hover:text-white hover:ease-in-out
                        hover:transition-all transition-colors duration-1000 hover:duration-1000
                        hover:animate-none animate-pulse">
            Load More
            </button></a>
            <div class="flex text-gray-700 text-sm mr-3">
                <form method="post" action="<%= downvote_comment_path(comment.id) %>">
                    <input type="hidden"
                        name="authenticity_token"
                        value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-regular fa-thumbs-down fa-xl"></i></button>
                </form>
                <span class="ml-1 text-black font-bold"><%= comment.votes.where(:value => -1).count %></span> <!-- Don't forget to add likes -->
            </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="grid grid-cols-4 m-4 gap-1 dark:bg-slate-900"> <!-- Subs for The User auto -->
    <% @user.posts.order(created_at: :desc).each do |post|%>
      <div class="flex bg-white shadow-lg rounded-lg mx-4 mb-[14px]
          max-w-md justify-start opacity-60 hover:opacity-100 cursor-text transition-opacity ease-in-out duration-700"><!--horizantil margin is just for display-->
        <div class="flex items-start px-4 py-6">
          <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="<%= @user.gravatar_url %>" alt="avatar">
          <div class="">
            <div class="flex items-center justify-between">
                <a href="<%= post_path(post.id)%>"><h2 class="text-lg font-semibold text-gray-900 -mt-1"><%= post.title %></h2></a>
                <small class="text-sm  text-blue-500"><%= post.calculate_current_time %></small>
            </div>
            <p class="text-gray-700">Joined <%= post.join_post_user %> </p>
            <p class="mt-3 text-gray-700 text-sm">
                <%= post.content %>
            </p>            
            <div class="mt-4 flex items-center">
              <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= upvote_post_path(post.id) %>">
                    <input type="hidden"
                          name="authenticity_token"
                          value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-thumbs-up fa-regular"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => 1).count %></span> <!-- Don't forget to add likes -->
              </div>
              <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= downvote_post_path(post.id) %>">
                    <input type="hidden"
                          name="authenticity_token"
                          value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-regular fa-thumbs-down"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => -1).count %></span> <!-- Don't forget to add likes -->
              </div>
              <div class="flex mr-2 text-gray-700 text-sm mr-8">
                  <a href="<%= post_path(post.id) %>" class="cursor-pointer">
                    <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                    </svg>
                  </a>
                  <span><%= post.comments.count%></span><!-- Don't forget to add comments -->
              </div>
              <div class="flex mr-2 text-gray-700 text-sm mr-4">
                  <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                  </svg>
                  <a href="<%= post.url%>"><span>Link</span></a>
              </div>
            </div>
          </div>
      </div>
    </div>
    <% end %>
  </div>
</section>