config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost', :port => 3000

  root to: "subs#index"

  devise_scope :user do
    # redirect signing out users back to sign-in
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end

  devise_for :users
  resources :users, :only => [:show]
  resources :subs do
    member do
      post "subscribe"
    end
    collection do 
      post "search"
    end
  end
  resources :posts, except: [:index] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  resources :comments, :only => [:create,:show] do 
    member do 
      post "upvote"
      post "downvote"
    end
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string(100)      not null
#  description  :string(500)      not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  avatar       :string
#  image_date   :text
#  slug         :string
#  subscriptors :integer          default([]), is an Array
#
class Sub < ApplicationRecord
    extend FriendlyId
    validates :title, presence: true
    validates :description, presence: true
    validates :moderator_id, presence: true
    
friendly_id :title, use: %i[slugged history]
    
    belongs_to :moderator,
        :class_name => 'User',
        :primary_key => :id,
        :foreign_key => :moderator_id

    has_many :post_subs,
            :class_name => 'PostSub', :foreign_key => :sub_id,:inverse_of => :sub
    has_many :posts, :through => :post_subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :authenticate_user!
    before_action :clarify_user!, only: [:edit, :update]

    def index
        @all_subs = Sub.all
        if !params[:q].present?
            @subs = Sub.page(params[:page]).per(4)
            respond_to do |format|
                format.html {
                    render :index
                }
                format.json {
                    if current_user.is_admin?
                        render json: @all_subs
                    else
                        render plain: "You are being hacky dude! 👺🚷" ,:status => :forbidden
                    end
                }
            end
        end
    end

    def show
        @sub = Sub.friendly.find(params[:id])
        if params[:id] != @sub.slug
            return redirect_to @sub, :status => :moved_permanently
        end
    end

    def new
        @sub = Sub.new
        render :new
    end

    def subscribe
        @sub = Sub.find(params[:id])
        if !@sub.subscriptors.include?(current_user.id)
            @sub.subscriptors << current_user.id
            @sub.save!
            redirect_to subs_path
        else
            flash[:notice] = "Subscription has already been did"
            redirect_to subs_path
        end
    end

    def search
        if params[:search].present?
            @subs = Sub.where("title ILIKE '%#{params[:search]}%'")
            @posts = Post.where("title ILIKE '%#{params[:search]}%'")
        else
            @subs = []
            @posts = []
        end
        respond_to do |format|
            format.turbo_stream do 
                render turbo_stream: turbo_stream.update("search_results",
                        partial: "subs/search_results",
                        locals: {subs: @subs, posts: @posts}
                )
            end
        end
    end

    def create
        @sub = Sub.new(subs_params)
        @sub.moderator_id = current_user.id

        if @sub.save
            flash[:notice] = "Sub Created Successfully 🎒"
            redirect_to sub_url(@sub.id)
        else
            # UserMailer.with(user: current_user,sub: @sub).notify_sub_error.deliver_now
            flash[:error] = "Failed to Create Sub 🔫"
            render :new
        end
    end

    def edit
        @sub = Sub.find_by(:id => params[:id])
        render :edit
    end

    def update
        @sub = Sub.find_by(:id => params[:id])

        if @sub.update(subs_params_update)
            # UserMailer.with(user: current_user,sub: @sub).notify_sub_update.deliver_now
            flash[:notice] = "Sub Updated Successfully 👽🔪"
            redirect_to sub_path(@sub.id)
        else
            # UserMailer.with(user: current_user,sub: @sub).notify_sub_update_error.deliver_now
            flash[:error] = "Failed To Update Sub 🧨"
            render :edit
        end
    end

    private

    def subs_params
        params.require(:subs).permit(:title,:description,:moderator_id)
    end

    def subs_params_update
        params.require(:subs).permit(
            :title,
            :description
        )
    end
    def clarify_user!
        return if current_user.subs.find_by(:id => params[:id])
        render json: 'Forbidden' ,status: :forbidden
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_search_results.html.erb
<div class="">
    <div class="inline-flex flex-col justify-center relative text-gray-500 rounded ">
        <% if !@subs.empty? && !@posts.empty? %>
            <ul class="bg-white border border-gray-100 w-full mt-2 rounded-lg">
                <% @subs.each do |sub_model| %>
                    <% if sub_model.subscriptors.include?(current_user.id) %>
                        <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse">
                            <i class="fas fa-subscript"></i>
                            <a href="<%= sub_path(sub_model.id) %>"><b class="text-green-400"><%= highlight(sub_model.title.slice(0..4),params[:search]) %></b><%= highlight(sub_model.title.slice(4..sub_model.title.length),params[:search]) %></a>
                        </li>
                    <% else %>
                        <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse">
                            <div class="flex justify-between">
                                <i class="fas fa-blog"></i>
                                <a class="mr-[145px]" href="<%= sub_path(sub_model.id) %>"><b class="text-rose-400 "><%= highlight(sub_model.title.slice(0..4),params[:search]) %></b><%= highlight(sub_model.title.slice(4..sub_model.title.length),params[:search]) %></a>
                                <form action="<%= subscribe_sub_path(sub_model.id) %>" method="post">
                                    <input type="hidden"
                                        name="authenticity_token"
                                            value="<%= form_authenticity_token %>">
                                    <input type="submit"
                                                value="Subscribe"
                                                    class="inline-block text-white font-bold border-[3px] border-orange-500
                                                    rounded-lg text-lg pr-[20px] pl-[20px] hover:animate-pulsate bg-orange-500 cursor-pointer"/>
                                </form>
                            </div>
                        </li>
                    <% end %>
                <% end %>
            </ul>
            <ul class="bg-white border border-gray-100 w-full mt-2 rounded-lg">
                <% @posts.each do |post| %>
                    <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse animate-none">
                        <i class="fas fa-subscript"></i>
                        <a href="<%= post_path(post.id) %>"><b class="text-blue-400"><%= highlight(post.title.slice(0..4),params[:search]) %></b><%= highlight(post.title.slice(4..post.title.length),params[:search]) %></a>
                    </li>
                <% end %>
            </ul>
        <% elsif @subs.empty? %>
            <ul class="bg-white border border-gray-100 w-full mt-2 rounded-lg">
                <% @posts.each do |post| %>
                    <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse animate-none">
                        <i class="fas fa-subscript"></i>
                        <a href="<%= post_path(post.id) %>"><b class="text-blue-400"><%= highlight(post.title.slice(0..4),params[:search]) %></b><%= highlight(post.title.slice(4..post.title.length),params[:search]) %></a>
                    </li>
                <% end %>
            </ul>
        <% elsif @posts.empty? %>
            <ul class="bg-white border border-gray-100 w-full mt-2 rounded-lg">
                <% @subs.each do |sub_model| %>
                    <% if sub_model.subscriptors.include?(current_user.id) %>
                        <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse">
                            <i class="fas fa-subscript"></i>
                            <a href="<%= sub_path(sub_model.id) %>"><b class="text-green-400"><%= highlight(sub_model.title.slice(0..4),params[:search]) %></b><%= highlight(sub_model.title.slice(4..sub_model.title.length),params[:search]) %></a>
                        </li>
                    <% else %>
                        <li class="pl-8 pr-2 py-1 border-b-2 ml-1 border-gray-100 relative cursor-pointer hover:bg-yellow-50 hover:text-gray-900 hover:animate-pulse">
                            <div class="flex justify-between">
                                <i class="fas fa-blog"></i>
                                <a class="mr-[145px]" href="<%= sub_path(sub_model.id) %>"><b class="text-rose-400 "><%= highlight(sub_model.title.slice(0..4),params[:search]) %></b><%= highlight(sub_model.title.slice(4..sub_model.title.length),params[:search]) %></a>
                                <form action="<%= subscribe_sub_path(sub_model.id) %>" method="post">
                                    <input type="hidden"
                                        name="authenticity_token"
                                            value="<%= form_authenticity_token %>">
                                    <input type="submit"
                                                value="Subscribe"
                                                    class="inline-block text-white font-bold border-[3px] border-orange-500
                                                    rounded-lg text-lg pr-[20px] pl-[20px] hover:animate-pulsate bg-orange-500 cursor-pointer"/>
                                </form>
                            </div>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/subs/_subscriptors.html.erb
<% sub.posts.includes(:author).order(created_at: :desc).each do |post| %>
   <div class="flex bg-white shadow-lg rounded-lg mx-4 mb-[14px] max-w-md justify-start"><!--horizantil margin is just for display-->
      <div class="flex items-start px-4 py-6">
         <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="<%= post.author.gravatar_url %>" alt="avatar">
         <div class="">
            <div class="flex items-center justify-between">
               <a href="<%= post_path(post)%>"><h2 class="text-lg font-semibold text-gray-900 -mt-1"><%= post.title %></h2></a>
               <small class="text-sm p-3 text-gray-700 text-blue-500"><%= post.calculate_current_time %></small>
            </div>
            <p class="text-gray-700">Joined <%= post.join_post_user %> </p>
            <p class="mt-3 text-gray-700 text-sm">
               <%= post.content %>
            </p>
            <div class="mt-4 flex items-center">
               <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= upvote_post_path(post.id) %>">
                     <input type="hidden"
                           name="authenticity_token"
                           value="<%= form_authenticity_token %>"/>
                     <button type="submit"><i class="fa-thumbs-up fa-regular"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => 1).count %></span> <!-- Don't forget to add likes -->
               </div>
               <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= downvote_post_path(post.id) %>">
                     <input type="hidden"
                        name="authenticity_token"
                        value="<%= form_authenticity_token %>"/>
                     <button type="submit"><i class="fa-regular fa-thumbs-down"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => -1).count %></span> <!-- Don't forget to add likes -->
               </div>
               <div class="flex mr-2 text-gray-700 text-sm mr-8">
                  <a href="<%= post_path(post.id) %>" class="cursor-pointer">
                     <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                     </svg>
                  </a>
                  <span><%= post.comments.count%></span><!-- Don't forget to add comments -->
               </div>
               <div class="flex mr-2 text-gray-700 text-sm mr-4">
                  <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                     <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                  </svg>
                  <a href="<%= post.url%>"><span>Link</span></a>
               </div>
            </div>
         </div>
      </div>
   </div>
<% end %>

app/views/subs/edit.html.erb
<body class="font-mono bg-gray-400">
		<!-- Container -->
		<div class="container mx-auto">
			<div class="flex justify-center px-6 mt-4">
				<!-- Row -->
				<div class="w-full xl:w-3/4 lg:w-11/12 flex h-[750px]">
					<!-- Col -->
					<div
						class="w-full h-auto bg-gray-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
						style="background-image: url('https://external-preview.redd.it/xm7e2Q-SV7zMt8T0TH1i_1mpoAHeGAGIBOh59nwYs3o.jpg?auto=webp&s=0421a95d23c865d1a6da2e268bc24e8d01096500')"
					></div>
					<!-- Col -->
					<div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none">
 						<h3 class="pt-4 text-2xl text-center">New Sub!</h3>
						<form class="px-8 pt-6 pb-8 mb-4 bg-white rounded" action="<%= sub_path(@sub.id) %>" method="POST">
                            <input type="hidden"
                                    name="_method"
                                        value="PATCH">
                            <p class="text-green-600 font-bold text-lg inline"><%= notice %></p>
                            <input type="hidden"
                                    name="authenticity_token"
                                        value="<%= form_authenticity_token %>">

                            <label for="sub_title" class="block mb-2 text-sm font-bold text-gray-700">Title</label>
                            <input type="text"
                                    name="subs[title]"
                                        class="border-2 border-gray-200 rounded mb-10"
                                            id="sub_title"
                                                required="required"
                                                    value="<%= @sub.title %>">

                            <label for="sub_description" class="block mb-2 text-sm font-bold text-gray-700">Description</label>
                            <textarea class="border-2 border-gray-200 w-[430px] h-[400px] font-bold text-xl mb-5" required="required" name="subs[description]" id="sub_description"><%= @sub.description %></textarea>
                            <br />

                            <input type="submit" value="SAVE" class="inline-block text-gray-500 font-bold border-[3px] border-[#3c67e3]
                                        rounded-lg text-lg pr-[20px] pl-[20px] m-[13px]
                                        pt-[6px] pb-[6px] hover:animate-pulsate cursor-pointer">
            </form>
					</div>
				</div>
			</div>
		</div>
	</body>

app/views/subs/index.html.erb
<section class="text-black font-medium text-lg m-3 ml-[170px] dark:text-white">
    <div class="flex justify-between">
        <h4 class="text-sm text-gray-700 ml-[50px] pb-4 font-bold">Trending Today 📈</h4>
        <a href="<%= new_sub_path %>"
                class="inline-block text-black font-bold bg-gradient-to-r from-rose-500 to-blue-500
                    rounded-lg text-lg pr-[20px] pl-[20px] m-[13px] pt-[6px] pb-[6px] hover:animate-pulsate">
                        <button type="button" class="font-bold">C Sub 😎</button></a>
    </div>
    <div class=""> <!-- All The Subs Container-->
        <%= paginate @subs %>
        <div class="container m-auto h-[50px] grid grid-cols-4"> <!-- Container of the subs cards -->
            <% @subs.order(created_at: :desc).includes(:moderator).each do |sub| %>
                <a href="<%= sub_path(sub) %>">
                    <div class="w-[238px] h-[200px] ml-10">  <!-- Image of the sub-->
                        <img class="h-[150px] rounded-lg w-[230px] z-[1] absolute" src="<%= sub.moderator.gravatar_url%>"/>
                        <div class="relative z-10 w-40">
                            <h4 class="font-bold text-gray-900 ml-2 dark:text-white text-sm first-letter:uppercase"><%= sub.title %></h4>
                            <% if sub.description.length > 36 %>
                                <p class="text-sm text-gray-500 ml-2 dark:text-white"><%= sub.description.slice(0..30)%> ...</p>
                            <% elsif sub.description.length > 20 %>
                                <p class="text-sm text-gray-500 ml-2 dark:text-white"><%= sub.description.slice(0..40)%> ...</p>
                            <% else %>  
                                <p class="text-sm text-gray-500 ml-2 dark:text-white"><%= sub.description%> ...</p>
                            <% end %>
                            <div class="flex">
                                <img class="w-12 h-12 rounded-full relative top-5 left-3 object-cover mr-4 shadow hover:blur-sm hover:cursor-pointer" src="<%= sub.moderator.gravatar_url %>" alt="user who comment"/>
                                <p class="text-sm ml-1 dark:text-white relative top-8  text-slate-900">
                                    Score: <span class="text-blue-700"><%= sub.moderator.score %></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            <% end %>
        </div>
    </div>
</section>
<section class="text-black font-medium text-lg m-[4.5rem] ml-[4.5rem] dark:text-white mt-[7.5rem]">
    <h4 class="text-sm text-gray-700 ml-[50px] pb-4 font-bold">Popular posts 📈</h4>
    <div class="grid grid-cols-4 dark:bg-slate-900">
    <% Sub.all.order(created_at: :desc).each do |sub| %>
        <% if sub.subscriptors.include?(current_user.id) %>
            <%= render 'subscriptors', sub: sub %>
        <% end %>
    <% end %>
</section>

app/views/subs/new.html.erb
<body class="font-mono bg-gray-400">
		<div class="container mx-auto">
			<div class="flex justify-center px-6 mt-4">
				<div class="w-full xl:w-3/4 lg:w-11/12 flex h-[750px]">
					<div
						class="w-full h-auto bg-gray-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
						style="background-image: url('https://external-preview.redd.it/xm7e2Q-SV7zMt8T0TH1i_1mpoAHeGAGIBOh59nwYs3o.jpg?auto=webp&s=0421a95d23c865d1a6da2e268bc24e8d01096500')"
					></div>
					<div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none">
 						<h3 class="pt-4 text-2xl text-center">New Sub!</h3>
						<form class="px-8 pt-6 pb-8 mb-4 bg-white rounded" action="<%= subs_path %>" method="POST">
                            <p class="text-green-600 font-bold text-lg inline"><%= notice %></p>
                            <input type="hidden"
                                    name="authenticity_token"
                                        value="<%= form_authenticity_token %>">

                            <label for="sub_title" class="block mb-2 text-sm font-bold text-gray-700">Title</label>
                            <input type="text"
                                    name="subs[title]"
                                        class="border-2 border-gray-200 rounded mb-10"
                                            id="sub_title"
                                                required="required">

                            <label for="sub_description" class="block mb-2 text-sm font-bold text-gray-700">Description</label>
                            <textarea class="border-2 border-gray-200 w-[430px] h-[400px] font-bold text-xl mb-5" required="required" name="subs[description]" id="sub_description"></textarea>
                            <br />

                            <input type="submit" value="SAVE" class="inline-block text-gray-500 font-bold border-[3px] border-[#3c67e3]
                                        rounded-lg text-lg pr-[20px] pl-[20px] m-[13px]
                                        pt-[6px] pb-[6px] hover:animate-pulsate cursor-pointer">
          	</form>
					</div>
				</div>
			</div>
		</div>
	</body>

app/views/subs/show.html.erb
<% moderator_sub = @sub.moderator %>

<div class="bg-white h-[143px] flex justify-between dark:bg-slate-900"> <!-- Profile Subs -->
   <div class="p-7">  <!-- The Subs Information -->
      <h1 class="uppercase font-bold text-xl dark:text-white">
            subs/<%= @sub.title %>
      </h1>
      <p class="lowercase pt-2 text-gray-700">
            <span class="font-normal dark:text-white"><%= @sub.description %></span>
      </p>
      <div class="flex">
         <p class="pt-1 text-gray-700 dark:text-white">
               Moderator by <em
                           class="font-light text-blue-400">
                              <a href="<%= user_path(moderator_sub.id) %>">
                                       <%= moderator_sub.username %></a></em>
               <% if @sub.moderator.username == current_user.username %>
                  <span class="ml-3 font-light text-blue-400 before:content-['🧨']">
                     <a href="<%= edit_sub_path(@sub.id) %>">Edit Sub</a>
                  </span>
               <% end %> 
         </p>
         <p class="font-bold text-base ml-3 mt-1 text-gray-500">
            <span class="text-sky-500"><%= @sub.subscriptors.count %></span> members
         </p>
      </div>
   </div>

   <div class=""> <!-- The Subscription Button -->
      <form action="<%= subscribe_sub_path(@sub.id) %>" method="post">
         <input type="hidden"
                  name="authenticity_token"
                     value="<%= form_authenticity_token %>">
         <input type="submit" value="Subscribe" class="inline-block text-white font-bold border-[3px] border-orange-500
                  rounded-lg text-lg pr-[20px] pl-[20px] m-[24px]
                  pt-[6px] pb-[6px] hover:animate-pulsate bg-orange-500 cursor-pointer"/>
      </form>
   </div>
</div>
<section class="m-[35px] dark:bg-slate-900">
<a href="<%= new_post_path %>"
      class="inline-block text-white font-bold border-[2px] border-[#3293db]
            rounded text-lg pt-[6px] pb-[6px] hover:animate-pulsate
            bg-[#3293db] uppercase tracking-[tight] w-[200px] text-center"
            >Create Post</a>
</section>
<!-- post card -->
<div class="grid grid-cols-4 grid-rows-[auto] dark:bg-slate-900">
<% @sub.posts.includes(:author).order(created_at: :desc).each do |post| %>
   <div class="flex bg-white shadow-lg rounded-lg mx-4 mb-[14px] max-w-md justify-start"><!--horizantil margin is just for display-->
      <div class="flex items-start px-4 py-6">
         <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src="<%= post.author.gravatar_url %>" alt="avatar">
         <div class="">
            <div class="flex items-center justify-between">
               <a href="<%= post_path(post.id)%>"><h2 class="text-lg font-semibold text-gray-900 -mt-1"><%= post.title %></h2></a>
               <small class="text-sm p-3 text-gray-700 text-blue-500"><%= post.calculate_current_time %></small>
            </div>
            <p class="text-gray-700">Joined <%= post.join_post_user %> </p>
            <p class="mt-3 text-gray-700 text-sm">
               <%= post.content %>
            </p>
            <div class="mt-4 flex items-center">
               <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= upvote_post_path(post.id) %>">
                     <input type="hidden"
                           name="authenticity_token"
                           value="<%= form_authenticity_token %>"/>
                     <button type="submit"><i class="fa-thumbs-up fa-regular"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => 1).count %></span> <!-- Don't forget to add likes -->
               </div>
               <div class="flex text-gray-700 text-sm mr-3">
                  <form method="post" action="<%= downvote_post_path(post.id) %>">
                     <input type="hidden"
                        name="authenticity_token"
                        value="<%= form_authenticity_token %>"/>
                     <button type="submit"><i class="fa-regular fa-thumbs-down"></i></button>
                  </form>
                  <span class="ml-1 text-black font-bold"><%= post.votes.where(:value => -1).count %></span> <!-- Don't forget to add likes -->
               </div>
               <div class="flex mr-2 text-gray-700 text-sm mr-8">
                  <a href="<%= post_path(post.id) %>" class="cursor-pointer">
                     <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"/>
                     </svg>
                  </a>
                  <span><%= post.comments.count%></span><!-- Don't forget to add comments -->
               </div>
               <div class="flex mr-2 text-gray-700 text-sm mr-4">
                  <svg fill="none" viewBox="0 0 24 24" class="w-4 h-4 mr-1" stroke="currentColor">
                     <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                  </svg>
                  <a href="<%= post.url%>"><span>Link</span></a>
               </div>
            </div>
         </div>
      </div>
   </div>
<% end %>
</div>