config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost', :port => 3000

  root to: "subs#index"

  devise_scope :user do
    # redirect signing out users back to sign-in
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end

  devise_for :users
  resources :users, :only => [:show]
  resources :subs do
    member do
      post "subscribe"
    end
    collection do 
      post "search"
    end
  end
  resources :posts, except: [:index] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  resources :comments, :only => [:create,:show] do 
    member do 
      post "upvote"
      post "downvote"
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#
class Post < ApplicationRecord
    extend FriendlyId
    validates :title, :presence => true
    validates :subs, presence: { message: 'must have at least one sub'}
    friendly_id :title, use: %i[slugged history]

    belongs_to :author,
              :class_name => 'User',
              :primary_key => :id,
              :foreign_key => :author_id

    has_many :post_subs,
              :class_name => 'PostSub', :foreign_key => :post_id, :dependent => :destroy, :inverse_of => :post
    has_many :subs, :through => :post_subs
    has_many :comments
    has_many :votes, as: :votable

    # Is not finished Yey, still the bug of the (month date)
    def calculate_current_time
      if self.created_at.day == Time.now.day
        ("#{Time.now.hour - self.created_at.hour}h ago")
      elsif self.created_at.day < Time.now.day
        ("#{Time.now.day - self.created_at.day}d ago")
      else self.created_at.month < Time.now.month
        ("#{Time.now.month - self.created_at.month}m ago")
      end
    end

    def calculate_post_current_time
      if self.created_at.min < Time.now.min
        ("#{Time.now.min - self.created_at.min}m ago")
      elsif self.created_at.hour < Time.now.hour
        ("#{Time.now.hour - self.created_at.hour}h ago")
      elsif self.created_at.day < Time.now.day
        ("#{Time.now.day - self.created_at.day}d ago")
      end
    end

    def join_post_user
      Date.parse(self.created_at.strftime("%d/%m/%Y"))
    end

    def top_level_comments
      self.comments.
        where(parent_comment_id: nil)
    end

    def comments_by_parent_id
      comments_hash = Hash.new { |h,k| h[k] = [] }
      self.comments.each do |comment|
        comments_hash[comment.parent_comment_id] = comment
      end
      comments_hash
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.friendly.find(params[:id])
    @sub = Sub.friendly.find_by(:id => params[:sub_id])
    @comments_by_parent_id = @post.comments_by_parent_id

    if params[:id] != @post.slug
      return redirect_to @post, :status => :moved_permanently
    end
  end

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = current_user.posts.new(posts_params)

    if @post.save
      flash[:notice] = "Post Created Successfully ☄️"
      redirect_to post_path(@post.id)
    else
      flash[:error] = "Failed to Create Post"
      render :new
    end
  end

  def edit
    @post = Post.find_by(:id => params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(:id => params[:id])

    if @post.update(posts_params)
      flash[:notice] = "Update Successfully"
      redirect_to post_path(@post.id)
    else
      flash[:error] = "Failed to Update"
      redirect_to post_path(@post.id)
    end
  end

  def downvote
    vote(-1)
  end

  def upvote
    vote(1)
  end

  private

  def vote(direction)
    @post = Post.find(params[:id])
    @vote = @post.votes.find_or_initialize_by(user: current_user)

    unless @vote.update(value: direction)
      flash[:errors] = @vote.errors.full_messages
    end
    redirect_to comment_path(@post.id)
  end

  def posts_params
    params.require(:posts).permit(:title,:url, :content,:user_id,sub_ids: [])
  end

  def posts_params_edit
    params.require(:posts).permit(:url,:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<body class="font-mono bg-gray-400">
		<div class="container mx-auto">
			<div class="flex justify-center px-6 mt-4">
				<div class="w-full xl:w-3/4 lg:w-11/12 flex h-[750px]">
					<div
						class="w-full h-auto bg-gray-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
						style="background-image: url('https://external-preview.redd.it/xm7e2Q-SV7zMt8T0TH1i_1mpoAHeGAGIBOh59nwYs3o.jpg?auto=webp&s=0421a95d23c865d1a6da2e268bc24e8d01096500')"
					></div>
					<div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none">
 						<h3 class="pt-4 text-2xl text-center">New Post 🤖🗡</h3>
						<form class="px-8 pt-6 pb-8 mb-4 bg-white rounded" action="<%= post_path(@post.id) %>" method="POST">
                  <p class="text-green-600 font-bold text-lg inline"><%= notice %></p>
                  <input type="hidden"
                          name="authenticity_token"
                              value="<%= form_authenticity_token %>">
                  <input type="hidden"
                            name="_method"
                              value="PATCH">
                  <label for="post_title" class="block mb-2 text-sm font-bold text-gray-700">Title</label>
                  <input type="text"
                            name="posts[title]"
                                class="border-2 border-gray-200 rounded mb-4"
                                    id="post_title"
                                        required="required"
                                          value="<%= @post.title %>">
                  <label for="post_url" class="block mb-2 text-sm font-bold text-gray-700">URL</label>
                  <input type="text"
                            name="posts[url]"
                              class="border-2 border-gray-200 rounded mb-4"
                                  id="post_url"
                                    value="<%= @post.url%>">

                  <label for="post_content" class="block mb-2 text-sm font-bold text-gray-700">Content</label>
                  <textarea class="border-2 border-gray-200 w-[430px] h-[200px] font-bold text-xl mb-5"name="posts[content]" id="post_content"><%= @post.content%></textarea>
                  <br />
                  <input type="hidden"
                          name="posts[sub_ids][]"
                            value=""/>
                  <% Sub.all.each do |sub| %>
                    <label class="block">
                        <input type="checkbox"
                                name="posts[sub_ids][]"
                                  value="<%= sub.id%>"
                                    <%= "checked" if @post.sub_ids.include?(sub.id)%>/>
                        <%= sub.title %>
                    </label>
                  <% end %>

                  <br />
                  <input type="submit"
                            value="SAVE"
                              class="inline-block text-gray-500 font-bold border-[3px] border-[#3c67e3]
                                        rounded-lg text-lg pr-[20px] pl-[20px] m-[13px]
                                        pt-[6px] pb-[6px] hover:animate-pulsate cursor-pointer">
            </form>
					</div>
				</div>
			</div>
		</div>
	</body>

app/views/posts/new.html.erb
<body class="font-mono bg-gray-400">
		<div class="container mx-auto">
			<div class="flex justify-center px-6 mt-4">
				<div class="w-full xl:w-3/4 lg:w-11/12 flex h-[750px]">
					<div
						class="w-full h-auto bg-gray-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
						style="background-image: url('https://external-preview.redd.it/xm7e2Q-SV7zMt8T0TH1i_1mpoAHeGAGIBOh59nwYs3o.jpg?auto=webp&s=0421a95d23c865d1a6da2e268bc24e8d01096500')"
					></div>
					<div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none">
 				    <h3 class="pt-4 text-2xl text-center">New Post 🤖🗡</h3>
						<form class="px-8 pt-6 pb-8 mb-4 bg-white rounded" action="<%= posts_path %>" method="POST">
                  <p class="text-green-600 font-bold text-lg inline"><%= notice %></p>
                  <input type="hidden"
                          name="authenticity_token"
                              value="<%= form_authenticity_token %>">
                  <label for="post_title" class="block mb-2 text-sm font-bold text-gray-700">Title</label>
                  <input type="text"
                            name="posts[title]"
                                class="border-2 border-gray-200 rounded mb-4"
                                    id="post_title"
                                        required="required">
                  <label for="post_url" class="block mb-2 text-sm font-bold text-gray-700">URL</label>
                  <input type="text"
                            name="posts[url]"
                              class="border-2 border-gray-200 rounded mb-4"
                                  id="post_url">

                  <label for="post_content" class="block mb-2 text-sm font-bold text-gray-700">Content</label>
                  <textarea class="border-2 border-gray-200 w-[430px] h-[200px] font-bold text-xl mb-5"name="posts[content]" id="post_content"></textarea>
                  <br />
                  <% @subs.order(created_at: :desc).each do |sub| %>
                    <label class="block">
                        <input type="checkbox" name="posts[sub_ids][]" value="<%= sub.id%>"/>
                        <%= sub.title %>
                    </label>
                  <% end %>

                  <br />
                  <input type="submit"
                            value="SAVE"
                              class="inline-block text-gray-500 font-bold border-[3px] border-[#3c67e3]
                                        rounded-lg text-lg pr-[20px] pl-[20px] m-[13px]
                                        pt-[6px] pb-[6px] hover:animate-pulsate cursor-pointer">
            </form>
					</div>
				</div>
			</div>
		</div>
	</body>

app/views/posts/show.html.erb
<% sub_post = Sub.find_by(:id => @post.post_subs.last.sub_id.to_i)%>
<section class="container mx-auto">
  <div class="bg-white h-[450px] w-auto mt-7 pl-[49px] pt-[25px] rounded-lg"> <!-- The White background -->
    <div class="font-medium pb-2"> <!-- data component -->
      <p class="text-gray-500 hover:text-gray-900 hover:transition-all duration-1000">Posted by: <a href="<%= user_path(@post.author.slug)%>"><em class="text-blue-400"><%= current_user.username %></em></a>
          in: <a href="<%= sub_path(sub_post.id) %>" class="text-blue-400"><%= sub_post.title %></a>
          over <%= @post.calculate_post_current_time %>
      </p>
      <% if current_user.posts.find_by(:id => @post.id).present? %>
        <a href="<%= edit_post_path(@post.id)%>"><p class="pt-1">🧨Edit</p></a>
      <% end %>
    </div>
    <div class="font-bold text-xl text-gray-800">  <!-- Post.title -->
      <h1 class=""><%= @post.title %></h1>
    </div>
    <div> <!-- Post.content-->
      <p class="text-gray-600 hover:text-blue-400 hover:transition-all duration-700 shadow-outline"><%= @post.content %></p>
    </div>
    <div>
      <!-- comment form -->
      <div class="flex mx-auto items-center justify-center mt-4">
        <form class="w-full max-w-xl bg-white rounded-lg px-4 pt-8" action="<%= comments_path %>" method="post">
          <input type="hidden"
                    name="authenticity_token"
                        value="<%= form_authenticity_token %>"/>
          <div class="flex flex-wrap -mx-3 mb-6">
            <h2 class="px-4 pt-3 pb-2 text-gray-800 text-lg">Add a new comment</h2>
            <input type="hidden"
                    name="comments[post_id]"
                      value="<%= @post.id %>"/>
            <input type="hidden"
                    name="comments[parent_comment_id]"
                      value="">
            <div class="w-full md:w-full px-3 mb-2 mt-2">
              <textarea class="bg-gray-100 rounded border border-gray-400 leading-normal resize-none w-full h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white" name="comments[content]" placeholder='Type Your Comment' required></textarea>
            </div>
            <div class="w-full md:w-full flex items-start px-3">
              <div class="flex items-start w-1/2 text-gray-700 px-2 mr-auto">
                <svg fill="none" class="w-5 h-5 text-gray-600 mr-1" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                  </svg>
                  <p class="text-xs md:text-sm pt-px">You Know That I love Right ?.❤️‍🔥.</p>
                </div>
                <div class="-mr-1">
                  <input type='submit' class="bg-white text-gray-700 font-medium py-1 px-4 border border-gray-400 cursor-pointer rounded-lg tracking-wide mr-1 hover:bg-gray-100" value='Post Comment'>
                </div>
              </div>
            </form>
          </div>
        </div>
    </div> <!-- Commments Form Goes Here-->
</section>

<div class="container grid grid-cols-4 m-auto">
  <% @post.comments.where(parent_comment_id: nil).includes(:author).each do |comment|%>
    <div class="bg-white shadow-lg  w-[350px] mt-2 h-[230px] rounded-lg ml-3">
      <div class="flex items-start px-4 py-3 h-20 border-b-2 border-b-gray-400 animate-pulse w-[100%]">
        <img class="w-12 h-12 rounded-full object-cover mr-4 shadow hover:blur-sm hover:cursor-pointer" src="<%= comment.author.gravatar_url %>" alt="user who comment"/>
        <% if comment.author.online? %>
          <div class="flex">
            <h3 class="font-bold pt-2 text-lg inline-block">
              <a href="<%= user_path(comment.author.id) %>">users/<span class="hover:text-blue-300 cursor-pointer"><%= comment.author.username %>
                  </span></a>
            <span class="text-green-400 text-xs top-[-9px] relative ">●</span>
            <p class="text-xs text-slate-500"><span class="hover:text-blue-400"><%= comment.calculate_comment_current_time %></span></p>
          </div>
        <% else %>
          <div class="flex">
            <h3 class="font-bold pt-2 text-lg inline-block">
              <a href="<%= user_path(comment.author.id) %>">users/<span class="hover:text-blue-300 cursor-pointer"><%= comment.author.username %>
                  </span></a>
            <span class="text-rose-400 text-xs top-[-9px] relative ">●</span>
          </div>
        <% end %>
        </h3>
      </div>
      <div class="px-4 py-3 text-sm h-[75px]">
        <%= comment.content %>
      </div>
      <div class="flex mt-7 ml-2 mr-2 justify-between">
            <div class="flex text-gray-700 text-sm mr-3">
                <form method="post" action="<%= upvote_comment_path(comment.id) %>">
                    <input type="hidden"
                            name="authenticity_token"
                            value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-thumbs-up fa-regular fa-xl"></i></button>
                </form>
                <span class="ml-1 text-black font-bold"><%= comment.votes.where(:value => 1).count %></span> <!-- Don't forget to add likes -->
            </div>
            <a href="<%= comment_path(comment) %>" class="font-bold bg-blue-400 p-2 rounded-lg
                        hover:opacity-100 hover:bg-black hover:text-white hover:ease-in-out
                        hover:transition-all transition-colors duration-1000 hover:duration-1000
                        hover:animate-none animate-pulse">
            Load More
            </button></a>
            <div class="flex text-gray-700 text-sm mr-3">
                <form method="post" action="<%= downvote_comment_path(comment.id) %>">
                    <input type="hidden"
                        name="authenticity_token"
                        value="<%= form_authenticity_token %>"/>
                    <button type="submit"><i class="fa-regular fa-thumbs-down fa-xl"></i></button>
                </form>
                <span class="ml-1 text-black font-bold"><%= comment.votes.where(:value => -1).count %></span> <!-- Don't forget to add likes -->
            </div>
        </div>
    </div>
  <% end %>
</div>