config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost', :port => 3000

  root to: "subs#index"

  devise_scope :user do
    # redirect signing out users back to sign-in
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
  end

  devise_for :users
  resources :users, :only => [:show]
  resources :subs do
    member do
      post "subscribe"
    end
    collection do 
      post "search"
    end
  end
  resources :posts, except: [:index] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  resources :comments, :only => [:create,:show] do 
    member do 
      post "upvote"
      post "downvote"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('money.jpg') %>
    <script src="https://kit.fontawesome.com/bfe7d96b18.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-[#dae0e6] font-sans dark:bg-slate-900 ">
    <header class="bg-white sticky z-[1000] w-[100%] dark:bg-slate-900">
      <nav class="h-[68px] flex justify-between dark:bg-slate-900"> <!-- Navigation menu -->
        <div class="inline-flex p-2 ml-5">  <!-- logo and The Search Bar for Subs and sub-posts -->
          <svg width="50" height="50" viewBox="0 0 256 256" class="cursor-pointer hover:animate-spin dark:text-white">
            <defs>
            </defs>
              <g transform="translate(128 128) scale(0.67 0.67)" style="">
                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(-189.89999999999998 -189.9) scale(4.22 4.22)" >
                  <circle cx="45" cy="45" r="45" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,69,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) "/>
                  <path d="M 75.011 45 c -0.134 -3.624 -3.177 -6.454 -6.812 -6.331 c -1.611 0.056 -3.143 0.716 -4.306 1.823 c -5.123 -3.49 -11.141 -5.403 -17.327 -5.537 l 2.919 -14.038 l 9.631 2.025 c 0.268 2.472 2.483 4.262 4.955 3.993 c 2.472 -0.268 4.262 -2.483 3.993 -4.955 s -2.483 -4.262 -4.955 -3.993 c -1.421 0.145 -2.696 0.973 -3.4 2.204 L 48.68 17.987 c -0.749 -0.168 -1.499 0.302 -1.667 1.063 c 0 0.011 0 0.011 0 0.022 l -3.322 15.615 c -6.264 0.101 -12.36 2.025 -17.55 5.537 c -2.64 -2.483 -6.801 -2.36 -9.284 0.291 c -2.483 2.64 -2.36 6.801 0.291 9.284 c 0.515 0.481 1.107 0.895 1.767 1.186 c -0.045 0.66 -0.045 1.32 0 1.98 c 0 10.078 11.745 18.277 26.23 18.277 c 14.485 0 26.23 -8.188 26.23 -18.277 c 0.045 -0.66 0.045 -1.32 0 -1.98 C 73.635 49.855 75.056 47.528 75.011 45 z M 30.011 49.508 c 0 -2.483 2.025 -4.508 4.508 -4.508 c 2.483 0 4.508 2.025 4.508 4.508 s -2.025 4.508 -4.508 4.508 C 32.025 53.993 30.011 51.991 30.011 49.508 z M 56.152 62.058 v -0.179 c -3.199 2.405 -7.114 3.635 -11.119 3.468 c -4.005 0.168 -7.919 -1.063 -11.119 -3.468 c -0.425 -0.515 -0.347 -1.286 0.168 -1.711 c 0.447 -0.369 1.085 -0.369 1.544 0 c 2.707 1.98 6.007 2.987 9.362 2.83 c 3.356 0.179 6.667 -0.783 9.407 -2.74 c 0.492 -0.481 1.297 -0.47 1.779 0.022 C 56.655 60.772 56.644 61.577 56.152 62.058 z M 55.537 54.34 c -0.078 0 -0.145 0 -0.224 0 l 0.034 -0.168 c -2.483 0 -4.508 -2.025 -4.508 -4.508 s 2.025 -4.508 4.508 -4.508 s 4.508 2.025 4.508 4.508 C 59.955 52.148 58.02 54.239 55.537 54.34 z" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
                </g>
              </g>
          </svg>
          <a href="<%= root_url %>"><svg width="80" height="80" viewBox="0 0 285.484 90.503" class="pb-[35px] pl-2 cursor-pointer">
            <defs>
              <style>
                .a {
                  fill: #ff4500;
                }

                .b {
                  fill: #222;
                }
              </style>
            </defs>
              <title>Reddit</title>
              <circle class="a" cx="238.236" cy="17.302" r="10.647" />
              <path class="b" d="M86.817,62.554c5.183,0,8.2-3.876,7.976-7.69a25.549,25.549,0,0,0-.534-4.292C91.081,36.8,79.879,26.619,66.546,26.619c-15.8,0-28.615,14.3-28.615,31.942S50.743,90.5,66.546,90.5c9.9,0,16.97-3.605,22.116-9.256a6.154,6.154,0,0,0-1.012-9.2c-2.485-1.727-5.631-1.145-7.943.807-2.207,1.863-6.423,5.676-13.161,5.676-8.048,0-14.761-6.859-16.3-15.971ZM66.546,38.6c7.243,0,13.4,5.556,15.687,13.309H50.86C53.144,44.153,59.3,38.6,66.546,38.6Z" />
              <path class="b" d="M38.6,32.81a5.986,5.986,0,0,0-5-5.9c-8.721-1.315-16.873,1.941-21.615,7.836v-.8A5.989,5.989,0,1,0,0,33.939v49.01a6.145,6.145,0,0,0,5.619,6.212,5.989,5.989,0,0,0,6.359-5.978V57.9c0-11.188,8.414-20.374,19.96-19.126a5.373,5.373,0,0,0,1.183,0A5.987,5.987,0,0,0,38.6,32.81Z" />
              <path class="b" d="M244.225,39.262a5.989,5.989,0,0,0-11.978,0V83.183a5.989,5.989,0,0,0,11.978,0Z" />
              <path class="b" d="M155.053,5.989A5.989,5.989,0,0,0,149.064,0h0a5.989,5.989,0,0,0-5.989,5.989V32.735a20.892,20.892,0,0,0-15.306-6.116c-15.8,0-28.615,14.3-28.615,31.942S111.965,90.5,127.769,90.5a21.154,21.154,0,0,0,15.415-6.193,5.988,5.988,0,0,0,11.869-1.127ZM127.769,78.525c-9.188,0-16.637-8.939-16.637-19.964S118.581,38.6,127.769,38.6s16.636,8.938,16.636,19.964S136.957,78.525,127.769,78.525Z" />
              <path class="b" d="M217.606,5.989A5.989,5.989,0,0,0,211.617,0h0a5.989,5.989,0,0,0-5.989,5.989V32.735a20.889,20.889,0,0,0-15.306-6.116c-15.8,0-28.614,14.3-28.614,31.942S174.519,90.5,190.322,90.5a21.156,21.156,0,0,0,15.416-6.193,5.987,5.987,0,0,0,11.868-1.127ZM190.322,78.525c-9.188,0-16.636-8.939-16.636-19.964S181.134,38.6,190.322,38.6s16.637,8.938,16.637,19.964S199.511,78.525,190.322,78.525Z" />
              <path class="b" d="M274.654,83.183V38.6h5.324a5.445,5.445,0,0,0,5.494-4.969,5.325,5.325,0,0,0-5.312-5.679h-5.506V19.5a6.126,6.126,0,0,0-5.591-6.182,5.989,5.989,0,0,0-6.387,5.976v8.651h-4.959a5.445,5.445,0,0,0-5.495,4.97,5.324,5.324,0,0,0,5.312,5.678h5.142V83.183a5.989,5.989,0,0,0,5.989,5.989h0A5.989,5.989,0,0,0,274.654,83.183Z" />
          </svg></a>
        </div>
        <div class="">
          <form action="<%= search_subs_path %>" method="post" data-controller="search" data-search-target="form">
            <input type="search" placeholder="Search Reddit ..." name="search", data-action="input->search#make_debounce"
                class="mt-2 ml-20 w-[596px] h-[50px] bg-gray-100 rounded-lg hover:border-2
                      font-bold shadow shadow-cyan-50 hover:transtion-all ease-in-out indent-2.5"
                  />
            <i class="fa-solid fa-magnifying-glass fa-xl pl-10 m-[-80px]"></i>
          </form>
          <div id="search_results" class="text-white font-bold text-base ml-[100px] mt-2"></div>
        </div>
        <div class="pl-80 flex justify-end">  <!-- login and sign up buttons and an advertising icon -->
          <a href="#"><i class="fa-solid fa-2xl fa-rectangle-ad m-[34px] ml-[20px] mr-[20px] text-[skyblue] hover:animate-ping hover:text-rose-300"></i></a>
          <% if !user_signed_in? %>
            <a href="<%= login_url %>"
                  class="inline-block text-black font-bold bg-gradient-to-r from-cyan-500 to-blue-500
                      rounded-lg text-lg pr-[20px] pl-[20px] m-[13px] pt-[6px] pb-[6px] hover:animate-pulsate"
                    >Log In</a>
            <a href="<%= register_url %>"
                  class="inline-block text-black font-bold bg-gradient-to-l from-cyan-500 to-blue-500
                      rounded-lg text-lg pr-[20px] pl-[20px] m-[13px] pt-[6px] pb-[6px] hover:animate-pulsate-slow"
                      >Sign Up</a>
          <% else %>
            <form action="<%= destroy_user_session_path %>" method="POST">
              <input type="hidden"
                        name="authenticity_token"
                          value="<%= form_authenticity_token %>" />
              <input type="hidden"
                        name="_method"
                          value="DELETE"/>
              <input type="submit"
                        value="Sign Out"
                          class="inline-block text-black font-bold bg-gradient-to-r
                            rounded-lg text-lg pr-[20px] pl-[20px] m-[13px]
                            pt-[6px] pb-[6px] cursor-pointer hover:animate-pulsate-gray
                            from-sky-500 to-indigo-500 hover:from-violet-400
                            hover:to-sky-400 hover:transition-colors"/>
            </form>
            <a class="w-[70px]"
                href="<%= user_path(current_user.slug) %>">
                  <i class="fa-solid fa-user fa-2xl m-[32px] ml-[20px]
                      text-gray-500 cursor-pointer  hover:text-rose-300">
                    </i>
            </a>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>